apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ebs-staging

resources:
  - ../../base/apps/api-deployment.yaml
  - ../../base/apps/web-deployment.yaml
  - ../../base/apps/worker-deployment.yaml
  - ../../base/ingress/ingress-route.yaml
  - ../../base/autoscaling/hpa.yaml
  - ../../base/network-policies/zero-trust.yaml

namePrefix: staging-
