apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app.kubernetes.io/name: explore-bharat-safar
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ebs-workload-irsa-role
automountServiceAccountToken: true
