import { z } from 'zod';
export declare const EnvironmentSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "staging", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    DATABASE_URL: z.ZodString;
    REDIS_HOST: z.ZodDefault<z.ZodString>;
    REDIS_PORT: z.ZodDefault<z.ZodNumber>;
    REDIS_PASSWORD: z.ZodDefault<z.ZodString>;
    JWT_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    JWT_PUBLIC_KEY: z.ZodOptional<z.ZodString>;
    JWT_ACCESS_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    DATA_ENCRYPTION_KEY: z.ZodOptional<z.ZodString>;
    RAZORPAY_KEY_ID: z.ZodOptional<z.ZodString>;
    RAZORPAY_KEY_SECRET: z.ZodOptional<z.ZodString>;
    RAZORPAY_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    S3_BUCKET_MEDIA: z.ZodOptional<z.ZodString>;
    S3_BUCKET_CERTS: z.ZodOptional<z.ZodString>;
    S3_BUCKET_QUARANTINE: z.ZodOptional<z.ZodString>;
    AWS_REGION: z.ZodDefault<z.ZodString>;
    AWS_SES_REGION: z.ZodDefault<z.ZodString>;
    AWS_SES_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    AWS_SES_SECRET_KEY: z.ZodOptional<z.ZodString>;
    WHATSAPP_API_TOKEN: z.ZodOptional<z.ZodString>;
    JWT_SECRET: z.ZodDefault<z.ZodString>;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    REFRESH_TOKEN_EXPIRES_DAYS: z.ZodDefault<z.ZodNumber>;
    EMAIL_FROM: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "staging" | "production";
    PORT: number;
    DATABASE_URL: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_PASSWORD: string;
    JWT_ACCESS_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    AWS_REGION: string;
    AWS_SES_REGION: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    REFRESH_TOKEN_EXPIRES_DAYS: number;
    EMAIL_FROM: string;
    JWT_PRIVATE_KEY?: string | undefined;
    JWT_PUBLIC_KEY?: string | undefined;
    DATA_ENCRYPTION_KEY?: string | undefined;
    RAZORPAY_KEY_ID?: string | undefined;
    RAZORPAY_KEY_SECRET?: string | undefined;
    RAZORPAY_WEBHOOK_SECRET?: string | undefined;
    S3_BUCKET_MEDIA?: string | undefined;
    S3_BUCKET_CERTS?: string | undefined;
    S3_BUCKET_QUARANTINE?: string | undefined;
    AWS_SES_ACCESS_KEY?: string | undefined;
    AWS_SES_SECRET_KEY?: string | undefined;
    WHATSAPP_API_TOKEN?: string | undefined;
}, {
    DATABASE_URL: string;
    NODE_ENV?: "development" | "test" | "staging" | "production" | undefined;
    PORT?: number | undefined;
    REDIS_HOST?: string | undefined;
    REDIS_PORT?: number | undefined;
    REDIS_PASSWORD?: string | undefined;
    JWT_PRIVATE_KEY?: string | undefined;
    JWT_PUBLIC_KEY?: string | undefined;
    JWT_ACCESS_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    DATA_ENCRYPTION_KEY?: string | undefined;
    RAZORPAY_KEY_ID?: string | undefined;
    RAZORPAY_KEY_SECRET?: string | undefined;
    RAZORPAY_WEBHOOK_SECRET?: string | undefined;
    S3_BUCKET_MEDIA?: string | undefined;
    S3_BUCKET_CERTS?: string | undefined;
    S3_BUCKET_QUARANTINE?: string | undefined;
    AWS_REGION?: string | undefined;
    AWS_SES_REGION?: string | undefined;
    AWS_SES_ACCESS_KEY?: string | undefined;
    AWS_SES_SECRET_KEY?: string | undefined;
    WHATSAPP_API_TOKEN?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    REFRESH_TOKEN_EXPIRES_DAYS?: number | undefined;
    EMAIL_FROM?: string | undefined;
}>;
export type Environment = z.infer<typeof EnvironmentSchema>;
export declare function validateEnvironment(config: Record<string, unknown>, exitOnError?: boolean): Environment;
//# sourceMappingURL=env.schema.d.ts.map